### ISSUE TITLE
Assembler directives not recognized properly

### ISSUE THREAD

**Issue by Evian-Zhang** [gondow/highlightjs-x86asmatt#1]
Some assembler directives, such as `.p2align`, `.cfi_startproc`, contains digits and `_`, while the regex `\.[a-zA-Z]+\b` does not cover all.

**Comment by gondow** [comment]
Thank you for your feedback.
I modified it to `\\.[a-zA-Z][a-zA-Z_0-9]*\\b`

<img width="582" alt="image" src="https://github.com/gondow/highlightjs-x86asmatt/assets/7510305/3b0d2f4a-cd06-46f1-97eb-e844d35c179b">
